[package]
name = "connect4"
version = "0.1.0"
edition = "2024"

[dependencies]
futures-util = "0.3.32"
rand = "0.9.2"
thiserror = "2.0.18"
tokio = { version = "1.49.0", features = ["full"] }
tokio-util = "0.7.18"
warp = { version = "0.4.2", features = ["server", "websocket"] }
